#!/usr/bin/env python3
"""sc_connolly_validate.py — Cross-implementation comparison of Connolly SES SC vs PyRosetta SC.

Compares the Connolly-SES values shipped at ``data/sc_connolly_positives.csv``
against the PyRosetta ``InterfaceAnalyzerMover`` reference values shipped at
``data/sc_rosetta_reference.csv`` (generated by ``scripts/v3/sc_rosetta_extract.py``).
Both files cover the full positive cohort (N = 1,129); this script merges them on
``file``, computes Pearson r, Spearman rho, and MAE, and saves the
Rosetta-vs-Connolly scatter to ``docs/figures/sc_validation.{pdf,png}``
plus a mirror at ``figures/sc_validation.png``.

Usage
-----
    python scripts/v3/sc_connolly_validate.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import pearsonr, spearmanr

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).parent.parent.parent  # Open-Binder/
ROSETTA_CSV = BASE_DIR / "data" / "sc_rosetta_reference.csv"
CONNOLLY_CSV = BASE_DIR / "data" / "sc_connolly_positives.csv"
DOCS_FIG_DIR = BASE_DIR / "docs" / "figures"
MIRROR_FIG_DIR = BASE_DIR / "figures"
DOCS_FIG_DIR.mkdir(parents=True, exist_ok=True)
MIRROR_FIG_DIR.mkdir(parents=True, exist_ok=True)


def load_pair(rosetta_csv: Path, connolly_csv: Path) -> pd.DataFrame:
    """Merge Rosetta SC reference and Connolly SC on ``file``."""
    ros = pd.read_csv(rosetta_csv)
    if "sc_rosetta" not in ros.columns:
        raise ValueError(
            f"{rosetta_csv} missing 'sc_rosetta' column — did you run "
            f"scripts/v3/sc_rosetta_extract.py?"
        )
    ros = ros[["file", "sc_rosetta"]]

    con = pd.read_csv(connolly_csv)
    # The Connolly file uses 'sc_ses' for the SC value (it has been renamed in
    # past versions; tolerate either header).
    if "sc_ses" in con.columns:
        con = con[["file", "sc_ses"]].rename(columns={"sc_ses": "sc_connolly"})
    elif "sc" in con.columns:
        con = con[["file", "sc"]].rename(columns={"sc": "sc_connolly"})
    else:
        raise ValueError(
            f"{connolly_csv} missing 'sc_ses' or 'sc' column — cannot proceed."
        )

    df = ros.merge(con, on="file", how="inner").dropna(
        subset=["sc_rosetta", "sc_connolly"]
    )
    return df


def make_scatter(
    df: pd.DataFrame,
    r: float,
    rho: float,
    n: int,
    out_paths: list[Path],
    label: str,
) -> None:
    """Save the Rosetta vs Connolly scatter plot."""
    fig, ax = plt.subplots(figsize=(5.5, 5.5))
    x = df["sc_rosetta"].values
    y = df["sc_connolly"].values
    ax.scatter(x, y, alpha=0.45, s=22, edgecolors="none", color="steelblue")

    lo = float(min(x.min(), y.min())) - 0.05
    hi = float(max(x.max(), y.max())) + 0.05
    ax.plot([lo, hi], [lo, hi], "k--", lw=0.8, alpha=0.5, label="y = x")
    ax.set_xlim(lo, hi)
    ax.set_ylim(lo, hi)
    ax.set_aspect("equal")
    ax.set_xlabel("PyRosetta InterfaceAnalyzer SC (Lawrence–Colman)")
    ax.set_ylabel("OpenBinder Connolly SES SC (sc_connolly)")
    title_parts = []
    if label:
        title_parts.append(label)
    title_parts.append(f"r = {r:.3f}, ρ = {rho:.3f}, N = {n}")
    ax.set_title(" — ".join(title_parts), fontsize=10)
    ax.legend(loc="lower right", fontsize=8)

    plt.tight_layout()
    for p in out_paths:
        plt.savefig(str(p), dpi=300 if p.suffix == ".png" else None)
    plt.close()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--rosetta-csv",
        type=Path,
        default=ROSETTA_CSV,
        help="Path to PyRosetta SC reference CSV (default: data/sc_rosetta_reference.csv)",
    )
    parser.add_argument(
        "--connolly-csv",
        type=Path,
        default=CONNOLLY_CSV,
        help="Path to Connolly SC CSV (default: data/sc_connolly_positives.csv)",
    )
    parser.add_argument(
        "--label",
        type=str,
        default="",
        help="Optional variant label prepended to the figure title.",
    )
    args = parser.parse_args()

    df = load_pair(args.rosetta_csv, args.connolly_csv)
    n = len(df)
    if n < 5:
        raise SystemExit(f"Too few rows ({n}) to compute correlations.")

    r, p_r = pearsonr(df["sc_rosetta"], df["sc_connolly"])
    rho, p_rho = spearmanr(df["sc_rosetta"], df["sc_connolly"])
    mae = float(np.mean(np.abs(df["sc_rosetta"] - df["sc_connolly"])))
    mean_ros = float(df["sc_rosetta"].mean())
    mean_con = float(df["sc_connolly"].mean())

    print("=" * 60)
    print(f"Cross-implementation SC validation (full positive cohort)")
    print(f"  Rosetta CSV : {args.rosetta_csv}")
    print(f"  Connolly CSV: {args.connolly_csv}")
    print(f"  N           = {n}")
    print(f"  Pearson r   = {r:.4f}  (p={p_r:.2e})")
    print(f"  Spearman ρ  = {rho:.4f}  (p={p_rho:.2e})")
    print(f"  MAE         = {mae:.4f}")
    print(f"  mean Rosetta sc  = {mean_ros:.4f}")
    print(f"  mean Connolly sc = {mean_con:.4f}")

    out_paths = [
        DOCS_FIG_DIR / "sc_validation.pdf",
        DOCS_FIG_DIR / "sc_validation.png",
        MIRROR_FIG_DIR / "sc_validation.png",
    ]
    make_scatter(df, r, rho, n, out_paths, args.label)
    for p in out_paths:
        print(f"  wrote {p}")


if __name__ == "__main__":
    main()
